### ISSUE TITLE
Add Variable

### ISSUE THREAD

**Issue by kaqu** [miquido/futura#26]
Variable should be a new type or modification of Signals that provides error-free stream of changes done on given variable. It should also reproduce last value on subscription.

**Comment by kaqu** [comment]
Need to check if Variable fits current tools design. It is possible using Future and Signal flatMaps to cache state and use them as Variable substitute.

**Comment by KaQuMiQ** [comment]
It should not be part of this library. Maybe we should revisit it in future, but for now it is out of scope.
